//
//  CodeGenerator.swift
//  SFSymbolsGenerator
//
//  Created by Leo Ho on 2025/06/27.
//

import Foundation

/// A utility struct for generating Swift enumeration code from SF Symbols metadata.
///
/// `CodeGenerator` is responsible for creating well-formatted Swift enumeration
/// code that includes all SF Symbols with proper availability annotations.
/// The generated code ensures type safety and platform compatibility.
///
/// ## Overview
///
/// The generator creates Swift enumerations with the following features:
/// - Raw string values matching the original SF Symbol names
/// - `@available` annotations based on symbol introduction dates
/// - Proper handling of Swift keyword conflicts (e.g., `case`, `return`)
/// - Camel case conversion for enum case names
/// - Custom `allCases` property that respects availability constraints
///
/// ## Generated Code Structure
///
/// ```swift
/// public enum SFSymbols: String, CaseIterable {
///     /// SF Symbols's name：arrow.left
///     @available(iOS 13.0, macOS 10.15, *)
///     case arrowLeft = "arrow.left"
///
///     public static var allCases: [SFSymbols] {
///         var allCases: [SFSymbols] = []
///         if #available(iOS 13.0, macOS 10.15, *) {
///             allCases.append(.arrowLeft)
///         }
///
///         return allCases
///     }
/// }
/// ```
///
struct CodeGenerator {

    /// Generates Swift enumeration code for SF Symbols.
    ///
    /// This method creates a complete Swift enumeration with availability annotations
    /// for each symbol. The generated code includes proper documentation comments,
    /// availability checks, and a custom `allCases` implementation.
    ///
    /// - Parameters:
    ///   - symbols: An array of `SymbolTuple` objects containing symbol names and
    ///             their release dates, sorted by release date and name.
    ///   - releases: A dictionary mapping release dates to OS version requirements.
    ///   - enumName: The name to use for the generated enumeration (default: "SFSymbols").
    ///
    /// - Returns: A complete Swift source code string ready to be written to a file.
    ///
    /// ## Generated Features
    ///
    /// - **Documentation Comments**: Each enum case includes a comment with the original symbol name
    /// - **Availability Annotations**: Proper `@available` attributes for each symbol
    /// - **Name Conversion**: Symbol names are converted to valid Swift identifiers
    /// - **Keyword Handling**: Swift keywords are properly escaped with backticks
    /// - **Custom allCases**: Runtime-aware `allCases` property that respects availability
    ///
    /// ## Example
    ///
    /// ```swift
    /// let symbols = [SymbolTuple(symbol: "arrow.left", released: "2019")]
    /// let releases = ["2019": ["iOS": "13.0", "macOS": "10.15"]]
    /// let code = CodeGenerator.generate(from: symbols, releases: releases, enumName: "Icons")
    /// ```
    static func generate(
        from symbols: [SymbolTuple],
        releases: Releases,
        enumName: String
    ) -> String {
        var content = """
            // \(enumName).swift
            // Generated by SFSymbolsGenerator
            // Do not edit this file manually.

            import Foundation

            public enum \(enumName): String, CaseIterable {
            """

        for symbolTuple in symbols {
            let availability = releases[symbolTuple.released]?.availabilty ?? ""
            content += "\n    /// SF Symbols's name：\(symbolTuple.symbol)"
            content +=
                "\n    @\(availability)\n    case \(symbolTuple.symbol.replacementName) = \"\(symbolTuple.symbol)\"\n"
        }

        content += """

                public static var allCases: [\(enumName)] {
                    var allCases: [\(enumName)] = []
            """

        for symbolTuple in symbols {
            let availability = releases[symbolTuple.released]?.availabilty ?? ""
            content += "\n        if #\(availability) {"
            content += "\n            allCases.append(.\(symbolTuple.symbol.replacementName))"
            content += "\n        }"
        }

        content += """
                    
                    
                    return allCases
                }
            }
            """

        return content
    }
}
